name: Build and Release

on:
  push:
    tags:
      - '*'  # Triggers on any tag push
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-gnu' || 'x86_64-unknown-linux-gnu' }}
        override: true

    - name: Build
      run: cargo build --release --target ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-gnu' || 'x86_64-unknown-linux-gnu' }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os == 'windows-latest' && 'sonarr_radarr_auto_blocklist_windows.exe' || 'sonarr_radarr_auto_blocklist_linux' }}
        path: target/${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-gnu/release/sonarr_radarr_auto_blocklist.exe' || 'x86_64-unknown-linux-gnu/release/sonarr_radarr_auto_blocklist' }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Download Windows build
      uses: actions/download-artifact@v3
      with:
        name: sonarr_radarr_auto_blocklist_windows.exe
        path: ./windows

    - name: Download Linux build
      uses: actions/download-artifact@v3
      with:
        name: sonarr_radarr_auto_blocklist_linux
        path: ./linux

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows/sonarr_radarr_auto_blocklist_windows.exe
        asset_name: sonarr_radarr_auto_blocklist_windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux/sonarr_radarr_auto_blocklist_linux
        asset_name: sonarr_radarr_auto_blocklist_linux
        asset_content_type: application/octet-stream
